### ISSUE TITLE
make build-app not working  because of missing favicon.ico

### ISSUE THREAD

**Issue by clstaudt** [openandroidinstaller-dev/openandroidinstaller#22]
```
╰─ make build-app                                                                            (openandroidinstaller) 
poetry run pyinstaller openandroidinstaller/openandroidinstaller.py --noconsole --noconfirm --onefile --icon "/assets/favicon.ico" --add-data "openandroidinstaller/assets:assets" --add-binary "openandroidinstaller/bin/adb:bin" --add-binary "openandroidinstaller/bin/fastboot:bin" --add-binary "openandroidinstaller/bin/heimdall:bin"
Configuration file exists at /Users/cls/Library/Application Support/pypoetry, reusing this directory.

Consider moving configuration to /Users/cls/Library/Preferences/pypoetry, as support for the legacy directory will be removed in an upcoming release.
836 INFO: PyInstaller: 5.3
836 INFO: Python: 3.10.6 (conda)
856 INFO: Platform: macOS-12.6-arm64-i386-64bit
857 INFO: wrote /Users/cls/Documents/Work/Projects/PrototypeFund/Sandbox/openandroidinstaller/openandroidinstaller.spec
859 INFO: UPX is not available.
860 INFO: Extending PYTHONPATH with paths
['/Users/cls/Documents/Work/Projects/PrototypeFund/Sandbox/openandroidinstaller/openandroidinstaller']
1144 INFO: checking Analysis
1144 INFO: Building Analysis because Analysis-00.toc is non existent
1144 INFO: Initializing module dependency graph...
1145 INFO: Caching module graph hooks...
1150 INFO: Analyzing base_library.zip ...
3429 INFO: Processing pre-find module path hook distutils from '/Users/cls/miniforge3/envs/openandroidinstaller/lib/python3.10/site-packages/PyInstaller/hooks/pre_find_module_path/hook-distutils.py'.
3485 INFO: distutils: retargeting to non-venv dir '/Users/cls/miniforge3/envs/openandroidinstaller/lib/python3.10'
4027 INFO: Caching module dependency graph...
4088 INFO: running Analysis Analysis-00.toc
4093 INFO: Analyzing /Users/cls/Documents/Work/Projects/PrototypeFund/Sandbox/openandroidinstaller/openandroidinstaller/openandroidinstaller.py
4642 INFO: Processing pre-safe import module hook urllib3.packages.six.moves from '/Users/cls/miniforge3/envs/openandroidinstaller/lib/python3.10/site-packages/PyInstaller/hooks/pre_safe_import_module/hook-urllib3.packages.six.moves.py'.
5704 INFO: Processing pre-safe import module hook six.moves from '/Users/cls/miniforge3/envs/openandroidinstaller/lib/python3.10/site-packages/PyInstaller/hooks/pre_safe_import_module/hook-six.moves.py'.
6142 INFO: Processing module hooks...
6142 INFO: Loading module hook 'hook-cryptography.py' from '/Users/cls/miniforge3/envs/openandroidinstaller/lib/python3.10/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
7004 INFO: Loading module hook 'hook-regex.py' from '/Users/cls/miniforge3/envs/openandroidinstaller/lib/python3.10/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
7005 INFO: Loading module hook 'hook-certifi.py' from '/Users/cls/miniforge3/envs/openandroidinstaller/lib/python3.10/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
7006 INFO: Loading module hook 'hook-flet.py' from '/Users/cls/miniforge3/envs/openandroidinstaller/lib/python3.10/site-packages/flet/__pyinstaller'...
7007 INFO: Loading module hook 'hook-pkg_resources.py' from '/Users/cls/miniforge3/envs/openandroidinstaller/lib/python3.10/site-packages/PyInstaller/hooks'...
7419 INFO: Processing pre-safe import module hook win32com from '/Users/cls/miniforge3/envs/openandroidinstaller/lib/python3.10/site-packages/_pyinstaller_hooks_contrib/hooks/pre_safe_import_module/hook-win32com.py'.
7834 INFO: Loading module hook 'hook-xml.etree.cElementTree.py' from '/Users/cls/miniforge3/envs/openandroidinstaller/lib/python3.10/site-packages/PyInstaller/hooks'...
7834 INFO: Loading module hook 'hook-lib2to3.py' from '/Users/cls/miniforge3/envs/openandroidinstaller/lib/python3.10/site-packages/PyInstaller/hooks'...
7847 INFO: Loading module hook 'hook-_tkinter.py' from '/Users/cls/miniforge3/envs/openandroidinstaller/lib/python3.10/site-packages/PyInstaller/hooks'...
7902 INFO: checking Tree
7902 INFO: Building Tree because Tree-00.toc is non existent
7902 INFO: Building Tree Tree-00.toc
7907 INFO: checking Tree
7907 INFO: Building Tree because Tree-01.toc is non existent
7907 INFO: Building Tree Tree-01.toc
7938 INFO: checking Tree
7938 INFO: Building Tree because Tree-02.toc is non existent
7938 INFO: Building Tree Tree-02.toc
7939 INFO: Loading module hook 'hook-encodings.py' from '/Users/cls/miniforge3/envs/openandroidinstaller/lib/python3.10/site-packages/PyInstaller/hooks'...
8089 INFO: Loading module hook 'hook-distutils.util.py' from '/Users/cls/miniforge3/envs/openandroidinstaller/lib/python3.10/site-packages/PyInstaller/hooks'...
8092 INFO: Loading module hook 'hook-platform.py' from '/Users/cls/miniforge3/envs/openandroidinstaller/lib/python3.10/site-packages/PyInstaller/hooks'...
8092 INFO: Loading module hook 'hook-packaging.py' from '/Users/cls/miniforge3/envs/openandroidinstaller/lib/python3.10/site-packages/PyInstaller/hooks'...
8092 INFO: Loading module hook 'hook-pickle.py' from '/Users/cls/miniforge3/envs/openandroidinstaller/lib/python3.10/site-packages/PyInstaller/hooks'...
8094 INFO: Loading module hook 'hook-heapq.py' from '/Users/cls/miniforge3/envs/openandroidinstaller/lib/python3.10/site-packages/PyInstaller/hooks'...
8095 INFO: Loading module hook 'hook-difflib.py' from '/Users/cls/miniforge3/envs/openandroidinstaller/lib/python3.10/site-packages/PyInstaller/hooks'...
8096 INFO: Loading module hook 'hook-multiprocessing.util.py' from '/Users/cls/miniforge3/envs/openandroidinstaller/lib/python3.10/site-packages/PyInstaller/hooks'...
8097 INFO: Loading module hook 'hook-sysconfig.py' from '/Users/cls/miniforge3/envs/openandroidinstaller/lib/python3.10/site-packages/PyInstaller/hooks'...
8104 INFO: Loading module hook 'hook-xml.py' from '/Users/cls/miniforge3/envs/openandroidinstaller/lib/python3.10/site-packages/PyInstaller/hooks'...
8126 INFO: Loading module hook 'hook-distutils.py' from '/Users/cls/miniforge3/envs/openandroidinstaller/lib/python3.10/site-packages/PyInstaller/hooks'...
8142 INFO: Looking for ctypes DLLs
8152 INFO: Analyzing run-time hooks ...
8155 INFO: Including run-time hook '/Users/cls/miniforge3/envs/openandroidinstaller/lib/python3.10/site-packages/PyInstaller/hooks/rthooks/pyi_rth_inspect.py'
8156 INFO: Including run-time hook '/Users/cls/miniforge3/envs/openandroidinstaller/lib/python3.10/site-packages/PyInstaller/hooks/rthooks/pyi_rth_subprocess.py'
8156 INFO: Including run-time hook '/Users/cls/miniforge3/envs/openandroidinstaller/lib/python3.10/site-packages/PyInstaller/hooks/rthooks/pyi_rth_pkgutil.py'
8157 INFO: Including run-time hook '/Users/cls/miniforge3/envs/openandroidinstaller/lib/python3.10/site-packages/PyInstaller/hooks/rthooks/pyi_rth_multiprocessing.py'
8159 INFO: Including run-time hook '/Users/cls/miniforge3/envs/openandroidinstaller/lib/python3.10/site-packages/flet/__pyinstaller/rthooks/pyi_rth_localhost_fletd.py'
8159 INFO: Including run-time hook '/Users/cls/miniforge3/envs/openandroidinstaller/lib/python3.10/site-packages/PyInstaller/hooks/rthooks/pyi_rth_pkgres.py'
8161 INFO: Including run-time hook '/Users/cls/miniforge3/envs/openandroidinstaller/lib/python3.10/site-packages/PyInstaller/hooks/rthooks/pyi_rth__tkinter.py'
8168 INFO: Looking for dynamic libraries
8560 INFO: Looking for eggs
8560 INFO: Python library not in binary dependencies. Doing additional searching...
8562 INFO: Using Python library /Users/cls/miniforge3/envs/openandroidinstaller/lib/libpython3.10.dylib
8566 INFO: Warnings written to /Users/cls/Documents/Work/Projects/PrototypeFund/Sandbox/openandroidinstaller/build/openandroidinstaller/warn-openandroidinstaller.txt
8593 INFO: Graph cross-reference written to /Users/cls/Documents/Work/Projects/PrototypeFund/Sandbox/openandroidinstaller/build/openandroidinstaller/xref-openandroidinstaller.html
8607 INFO: Appending 'binaries' from .spec
8607 INFO: Appending 'datas' from .spec
8613 INFO: checking PYZ
8613 INFO: Building PYZ because PYZ-00.toc is non existent
8613 INFO: Building PYZ (ZlibArchive) /Users/cls/Documents/Work/Projects/PrototypeFund/Sandbox/openandroidinstaller/build/openandroidinstaller/PYZ-00.pyz
9039 INFO: Building PYZ (ZlibArchive) /Users/cls/Documents/Work/Projects/PrototypeFund/Sandbox/openandroidinstaller/build/openandroidinstaller/PYZ-00.pyz completed successfully.
9048 INFO: EXE target arch: arm64
9048 INFO: Code signing identity: None
9049 INFO: checking PKG
9049 INFO: Building PKG because PKG-00.toc is non existent
9049 INFO: Building PKG (CArchive) openandroidinstaller.pkg
18432 INFO: Building PKG (CArchive) openandroidinstaller.pkg completed successfully.
18437 INFO: Bootloader /Users/cls/miniforge3/envs/openandroidinstaller/lib/python3.10/site-packages/PyInstaller/bootloader/Darwin-64bit/runw
18437 INFO: checking EXE
18437 INFO: Building EXE because EXE-00.toc is non existent
18437 INFO: Building EXE from EXE-00.toc
18437 INFO: Copying bootloader EXE to /Users/cls/Documents/Work/Projects/PrototypeFund/Sandbox/openandroidinstaller/dist/openandroidinstaller
18437 INFO: Converting EXE to target arch (arm64)
18458 INFO: Removing signature(s) from EXE
18481 INFO: Appending PKG archive to EXE
18549 INFO: Fixing EXE headers for code signing
18555 INFO: Rewriting the executable's macOS SDK version (12.1.0) to match the SDK version of the Python library (11.0.0) in order to avoid inconsistent behavior and potential UI issues in the frozen application.
18555 INFO: Re-signing the EXE
18861 INFO: Building EXE from EXE-00.toc completed successfully.
18867 INFO: checking BUNDLE
18867 INFO: Building BUNDLE because BUNDLE-00.toc is non existent
18867 INFO: Building BUNDLE BUNDLE-00.toc
Traceback (most recent call last):
  File "/Users/cls/miniforge3/envs/openandroidinstaller/bin/pyinstaller", line 8, in <module>
    sys.exit(run())
  File "/Users/cls/miniforge3/envs/openandroidinstaller/lib/python3.10/site-packages/PyInstaller/__main__.py", line 178, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/Users/cls/miniforge3/envs/openandroidinstaller/lib/python3.10/site-packages/PyInstaller/__main__.py", line 59, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/Users/cls/miniforge3/envs/openandroidinstaller/lib/python3.10/site-packages/PyInstaller/building/build_main.py", line 934, in main
    build(specfile, distpath, workpath, clean_build)
  File "/Users/cls/miniforge3/envs/openandroidinstaller/lib/python3.10/site-packages/PyInstaller/building/build_main.py", line 856, in build
    exec(code, spec_namespace)
  File "/Users/cls/Documents/Work/Projects/PrototypeFund/Sandbox/openandroidinstaller/openandroidinstaller.spec", line 46, in <module>
    app = BUNDLE(
  File "/Users/cls/miniforge3/envs/openandroidinstaller/lib/python3.10/site-packages/PyInstaller/building/osx.py", line 103, in __init__
    self.__postinit__()
  File "/Users/cls/miniforge3/envs/openandroidinstaller/lib/python3.10/site-packages/PyInstaller/building/datastruct.py", line 173, in __postinit__
    self.assemble()
  File "/Users/cls/miniforge3/envs/openandroidinstaller/lib/python3.10/site-packages/PyInstaller/building/osx.py", line 128, in assemble
    self.icon = normalize_icon_type(self.icon, ("icns",), "icns", CONF["workpath"])
  File "/Users/cls/miniforge3/envs/openandroidinstaller/lib/python3.10/site-packages/PyInstaller/building/icon.py", line 34, in normalize_icon_type
    raise FileNotFoundError(f"Icon input file {icon_path} not found")
FileNotFoundError: Icon input file /assets/favicon.ico not found
make: *** [build-app] Error 1
```

**Comment by tsterbak** [comment]
Fixed: Change the path in the Makefile

**Comment by tsterbak** [comment]
Fixed: Change the path in the Makefile
